### ISSUE TITLE
Createsuperuser command fails due to no email

### ISSUE THREAD

**Issue by phiberjenz** [grantmcconnaughey/cookiecutter-django-vue-graphql-aws#6]
Manage.py createsuperuser doesn't ask for an email adress due to the REQUIRED_FIELDS not being set on the subclassed user model. This causes the createsuperuser command to fail since no email adress is given. Adding REQUIRED_FIELDS = ['email'] fixes this. Ref https://docs.djangoproject.com/en/3.0/topics/auth/customizing/#django.contrib.auth.models.CustomUser.REQUIRED_FIELDS

PR on its way!

**Comment by phiberjenz** [comment]
#7

**Comment by grantmcconnaughey** [comment]
Fixed in #7
